  const stations = [
    {
      name: 'あいお',
      translation: 'Aio',
      address: '山口市秋穂東1520-4',
      tel: '083-984-5704',
      time: '9:00 〜 18:00',
      parking: '24',
      cream: 'なし',
      images: [
        'img/stations_photo_new/01_aio_board.jpg',
        'img/stations_photo_new/01_aio_station.jpg',
      ],
      mapX: '39.1',
      mapY: '59.9',
      facilities: "park,shop,toilet,cafe,restaurant",
      official: 'https://michinoeki-aio.com/',
    },
    {
      name: 'あさひ',
      translation: 'Asahi',
      address: '萩市朝日大字佐々並2476-1',
      tel: '0838-56-0278',
      time: '7:30 〜 18:30',
      parking: '20',
      cream: 'バニラソフト',
      images: [
        'img/stations_photo_new/02_asahi_board.jpg',
        'img/stations_photo_new/02_asahi_station.jpg',
      ],
      mapX: '39.8',
      mapY: '39.1',
      facilities : "park,shop,toilet,restaurant,babyBed",
      official: 'https://www.hagishi.com/search/detail.php?d=1100186',
    },
    {
      name: '阿武町',
      translation: 'Abu',
      address: '阿武郡阿武町奈古2249',
      tel: '08388-2-0355',
      time: '10:00 〜 18:00',
      parking: '155',
      cream: 'バニラソフト',
      images: [
        'img/stations_photo_new/03_abu_board.jpg',
        'img/stations_photo_new/03_abu_station.jpg',
        'img/stations_photo_new/03_abu_cream.jpg',
        'img/stations_photo_new/03_abu_menu.jpg',
      ],
      mapX: '41.4',
      mapY: '20.6',
      facilities : "park,guide,shop,hotSpring,toilet,babyBed,cafe,restaurant",
      official: 'https://www.abucreation.com/',
    },
    {
      name: 'うり坊の郷',
      translation: 'Uribo no Sato',
      address: '萩市大字片保1124-1',
      tel: '08388-8-0114',
      time: '8:00 〜 17:00',
      parking: '29',
      cream: 'トマトソフト',
      images: [
        'img/stations_photo_new/04_uribou_board.jpg',
        'img/stations_photo_new/04_uribou_station.jpg',
        'img/stations_photo_new/04_uribou_cream.jpg',
        'img/stations_photo_new/04_uribou_menu.jpg',
      ],
      mapX: '49.3',
      mapY: '21.3',
      facilities : "shop,cafe,toilet",
      official: 'http://www.hagi.machi-navi.jp/html/specialty_85.html',
    },
    {
      name: 'おふく',
      translation: 'Ohuku',
      address: '美祢市於福町上4383-1',
      tel: '0837-56-5005',
      time: '9:00 〜 18:00',
      parking: '85',
      cream: '木いちごソフト',
      images: [
        'img/stations_photo_new/05_ohuku_board.jpg',
        'img/stations_photo_new/05_ohuku_station.jpg',
        'img/stations_photo_new/05_ohuku_cream.jpg',
        'img/stations_photo_new/05_ohuku_menu.jpg',
      ],
      mapX: '25.8',
      mapY: '41.5',
      facilities : "shop,hotSpring,toilet,babyBed,cafe,restaurant",
      official: 'https://www.michinoeki-ofuku.jp/',
    },
    {
      name: '上関海峡',
      translation: 'Kminoseki kaikyou',
      address: '熊毛郡上関町大字室津904-15',
      tel: '0820-62-1139',
      time: '8:30 〜 18:00',
      parking: '48',
      cream: 'ラムネソフト',
      images: [
        'img/stations_photo_new/06_kaminoseki_board.jpg',
        'img/stations_photo_new/06_kaminoseki_station.jpg',
        'img/stations_photo_new/06_kaminoseki_cream.jpg',
        'img/stations_photo_new/06_kaminoseki_menu.jpg',
      ],
      mapX: '75.5',
      mapY: '74.3',
      facilities : "guide,shop,toilet,cafe,restaurant",
      official: 'https://kaminoseki-kaikyo.jp/',
    },
    {
      name: '願成就温泉',
      translation: 'Ganjojuonsen',
      address: '山口市阿東徳佐上10002-116',
      tel: '083-957-0118',
      time: '10:30 〜 19:00',
      parking: '70',
      cream: 'バニラソフト',
      images: [
        'img/stations_photo_new/07_ganjyoujyu_board.jpg',
        'img/stations_photo_new/07_ganjyoujyu_station.jpg',
        'img/stations_photo_new/07_ganjyoujyu_cream.jpg',
        'img/stations_photo_new/07_ganjyoujyu_menu.jpg',
      ],
      mapX: '54.5',
      mapY: '26.7',
      facilities : "guide,shop,hotSpring,toilet,babyBed,restaurant",
      official: 'https://www.ganjojuonsen.com/',
    },
    {
      name: 'きくがわ',
      translation: 'Kikugawa',
      address: '下関菊川町大字上岡枝766-1',
      tel: '083-287-4649',
      time: '8:30 〜 17:00',
      parking: '70',
      cream: 'いちごソフト',
      images: [
        'img/stations_photo_new/08_kikugawa_board.jpg',
        'img/stations_photo_new/08_kikugawa_station.jpg',
        'img/stations_photo_new/08_kikugawa_cream.jpg',
        'img/stations_photo_new/08_kikugawa_menu.jpg',
      ],
      mapX: '17.9',
      mapY: '52',
      facilities : "guide,shop,toilet,cafe,restaurant",
      official: 'http://michinoekikikugawa.co.jp/',
    },
    {
      name: '北浦街道 豊北',
      translation: 'Kitaurakaido Hohoku',
      address: '下関市豊北町神田上314-1',
      tel: '083-786-0111',
      time: '8:30 〜 18:00 ※季節変動 有',
      parking: '141',
      cream: 'ラムネソフト',
      images: [
        'img/stations_photo_new/09_hohoku_board.jpg',
        'img/stations_photo_new/09_hohoku_station.jpg',
        'img/stations_photo_new/09_hohoku_cream.jpg',
        'img/stations_photo_new/09_hohoku_menu.jpg',
      ],
      mapX: '10.5',
      mapY: '37.3',
      facilities : "guide,shop,toilet,babyBed,cafe,restaurant",
      official: 'https://michinoeki-houhoku.jp/',
    },
    {
      name: 'きららあじす',
      translation: 'Kirara Ajisu',
      address: '山口阿知須10509-88',
      tel: '0836-66-1001',
      time: '8:30 〜 18:00',
      parking: '160',
      cream: 'かぼちゃソフト',
      images: [
        'img/stations_photo_new/10_kirara_board.jpg',
        'img/stations_photo_new/10_kirara_station.jpg',
        'img/stations_photo_new/10_kirara_cream.jpg',
        'img/stations_photo_new/10_kirara_menu.jpg',
      ],
      mapX: '33',
      mapY: '63.2',
      facilities : "shop,toilet,cafe,restaurant,babyBed",
      official: 'https://kiraraajisu.jp/',
    },
    {
      name: 'サザンセトとうわ',
      translation: 'Sazan Seto Towa',
      address: '大島郡周防大島町西方1958-77',
      tel: '0820-78-0033',
      time: '10:00 〜 18:00',
      timeNotes: '※売店',
      parking: '120',
      cream: 'みかんソフト',
      images: [
        'img/stations_photo_new/11_touwa_board.jpg',
        'img/stations_photo_new/11_touwa_station.jpg',
        'img/stations_photo_new/11_touwa_cream.jpg',
        'img/stations_photo_new/11_touwa_menu.jpg',
      ],
      mapX: '83',
      mapY: '72.0',
      facilities : "park,guide,shop,toilet,cafe,restaurant,babyBed",
      official: 'https://sazan-seto.com/',
    },
    {
      name: '潮彩市場防府',
      translation: 'Shiosai ichiba-hofu',
      address: '防府市新築地町2-3',
      tel: '0835-28-2100',
      time: '9:00 〜 18:00',
      timeNotes: '※飲食店は店舗により異なる',
      parking: '152',
      cream: 'バニラソフト',
      images: [
        'img/stations_photo_new/12_shiosai_board.jpg',
        'img/stations_photo_new/12_shiosai_station.jpg',
      ],
      mapX: '47',
      mapY: '58.5',
      facilities : "cafe,restaurant,park,guide,shop,toilet",
      official: 'https://www.shiosai-hofu.com/',
    },
    {
      name: 'センザキッチン',
      translation: 'Senzakitchen',
      address: '長門市仙崎4297-1',
      tel: '0837-27-0300',
      time: '9:00 〜 18:00',
      timeNotes: '※閉店時間は店舗により異なる',
      parking: '216',
      cream: 'コーヒーソフト',
      images: [
        'img/stations_photo_new/13_senzaki_board.jpg',
        'img/stations_photo_new/13_senzaki_station.jpg',
        'img/stations_photo_new/13_senzaki_cream.jpg',
        'img/stations_photo_new/13_senzaki_menu.jpg',
      ],
      mapX: '25.8',
      mapY: '28.8',
      facilities : "guide,shop,toilet,shower,babyBed,cafe,restaurant,museum",
      official: '',
    },
    {
      name: 'ソレーネ周南',
      translation: 'Solene Shunan',
      address: '周南市大字戸田2713',
      tel: '0834-83-3303',
      time: '8:00 〜 20:00',
      timeNotes: '※テナント店舗を除く',
      parking: '170',
      cream: '牧場ソフト',
      images: [
        'img/stations_photo_new/14_syuunan_board.jpg',
        'img/stations_photo_new/14_syuunan_station.jpg',
        'img/stations_photo_new/14_syuunan_cream.jpg',
        'img/stations_photo_new/14_syuunan_menu.jpg',
      ],
      mapX: '53.1',
      mapY: '59.2',
      facilities : "park,guide,shop,toilet,babyBed,cafe,restaurant",
      official: 'https://www.solene.jp/',
    },
    {
      name: '長門峡',
      translation: 'Chomonkyo',
      address: '山口市阿東生雲東分47-1',
      tel: '083-955-0777',
      time: '9:30 〜 18:00',
      parking: '81',
      cream: '梨ソフト',
      images: [
        'img/stations_photo_new/15_choumon_board.jpg',
        'img/stations_photo_new/15_choumon_station.jpg',
        'img/stations_photo_new/15_choumon_cream.jpg',
        'img/stations_photo_new/15_choumon_menu.jpg',
      ],
      mapX: '46.1',
      mapY: '37.2',
      facilities : "park,shop,toilet,restaurant,babyBed",
      official: 'https://kunkunodaichi.com/',
    },
    {
      name: '仁保の郷',
      translation: 'Niho no Sato',
      address: '山口市仁保中郷1034',
      tel: '083-929-0480',
      time: '8:30 〜 17:00',
      parking: '103',
      cream: 'バニラソフト',
      images: [
        'img/stations_photo_new/16_niho_board.jpg',
        'img/stations_photo_new/16_niho_station.jpg',
      ],
      mapX: '43.9',
      mapY: '44.7',
      facilities : "park,shop,toilet,cafe,restaurant,babyBed",
      official: 'https://www.nihonosato.com/',
    },
    {
      name: '萩往還',
      translation: 'Hagi Okan',
      address: '萩市大字椿字鹿背ヶ坂1258',
      tel: '0838-22-9889',
      time: '9:00 〜 18:00',
      parking: '64',
      cream: '萩夏みかんソフト',
      images: [
        'img/stations_photo_new/17_hagioukan_board.jpg',
        'img/stations_photo_new/17_hagioukan_station.jpg',
      ],
      mapX: '37.9',
      mapY: '32.7',
      facilities : "park,guide,shop,toilet,cafe,restaurant,museum,babyBed",
      official: 'https://www.hagioukan.com/wp/',
    },
    {
      name: '萩・さんさん三見',
      translation: 'Hagi Sansansanmi',
      address: '萩市三見1028-2',
      tel: '0838-27-0041',
      time: '9:00 〜 17:00',
      parking: '40',
      cream: 'クロワッサンソフト',
      images: [
        'img/stations_photo_new/18_sanmi_board.jpg',
        'img/stations_photo_new/18_sanmi_station.jpg',
        'img/stations_photo_new/18_sanmi_cream.jpg',
        'img/stations_photo_new/18_sanmi_menu.jpg',
      ],
      mapX: '32.4',
      mapY: '30.0',
      facilities : "shop,toilet,restaurant",
      official: 'https://www.akeishi.net/',
    },
    {
      name: '萩しーまーと',
      translation: 'Hagi seamart',
      address: '萩市椿東4160-61',
      tel: '0838-24-4937',
      time: '9:30 〜 18:00',
      timeNotes: '※金,土,日,祝は9:00~',
      parking: '88',
      cream: '萩夏みかんソフト',
      images: [
        'img/stations_photo_new/19_si-ma-to_board.jpg',
        'img/stations_photo_new/19_si-ma-to_station.jpg',
        'img/stations_photo_new/19_si-ma-to_cream.jpg',
        'img/stations_photo_new/19_si-ma-to_menu.jpg',
      ],
      mapX: '37.9',
      mapY: '26.2',
      facilities : "cafe,restaurant,park,shop,toilet,babyBed",
      official: 'http://seamart.axis.or.jp/',
    },
    {
      name: 'ハピネスふくえ',
      translation: 'Happness Fukue',
      address: '萩市大字福井下4014-2',
      tel: '0838-52-0356',
      time: '8:30 〜 17:00',
      parking: '43',
      cream: 'なし',
      images: [
        'img/stations_photo_new/20_hukue_board.jpg',
        'img/stations_photo_new/20_hukue_station.jpg',
        'img/stations_photo_new/20_hukue_menu.jpg',
      ],
      mapX: '41.6',
      mapY: '26.2',
      facilities : "restaurant,park,shop,toilet,babyBed",
      official: 'https://hagi-gochi.jp/buy/hapiness_fukue',
    },
    {
      name: 'ピュアラインにしき',
      translation: 'Pure Line Nishiki',
      address: '岩国市錦町府谷117',
      tel: '0827-71-0011',
      time: '9:00 〜 17:00',
      parking: '75',
      cream: 'バニラソフト',
      images: [
        'img/stations_photo_new/21_nishiki_board.jpg',
        'img/stations_photo_new/21_nishiki_station.jpg',
      ],
      mapX: '66.5',
      mapY: '42',
      facilities : "cafe,restaurant,park,shop,toilet,babyBed",
      official: 'https://pureline-nishiki.com/',
    },
    {
      name: '蛍街道西ノ市',
      translation: 'Hotarukaido Nishinoichi',
      address: '下関市豊田町大字中村876-4',
      tel: '083-767-0241',
      time: '8:30 〜 21:00',
      parking: '130',
      cream: 'ポッポブラック',
      images: [
        'img/stations_photo_new/22_hotaru_board.jpg',
        'img/stations_photo_new/22_hotaru_station.jpg',
        'img/stations_photo_new/22_hotaru_cream.jpg',
        'img/stations_photo_new/22_hotaru_menu.jpg',
      ],
      mapX: '20',
      mapY: '46',
      facilities : "cafe,restaurant,guide,shop,hotSpring,toilet,babyBed",
      official: 'https://toyota-hotaru.com/',
    },
    {
      name: 'みとう',
      translation: 'Mito',
      address: '美祢市美東町太田5480-1',
      tel: '08396-2-2500',
      time: '8:30 〜 17:30',
      parking: '97',
      cream: '栗ソフト',
      images: [
        'img/stations_photo_new/23_mitou_board.jpg',
        'img/stations_photo_new/23_mitou_station.jpg',
        'img/stations_photo_new/23_mitou_cream.jpg',
        'img/stations_photo_new/23_mitou_menu.jpg',
      ],
      mapX: '32.8',
      mapY: '44.6',
      facilities : "park,cafe,restaurant,guide,shop,toilet,babyBed",
      official: 'https://karusuto.com/spot/michinoekimito/',
    },
    {
      name: 'ゆとりパークたまがわ',
      translation: 'Yutori Park Tamagawa',
      address: '萩市大字下万2849-1',
      tel: '08387-2-1150',
      time: '8:30 〜 18:00',
      parking: '161',
      cream: 'ゆずきちソフト',
      images: [
        'img/stations_photo_new/24_tamagawa_board.jpg',
        'img/stations_photo_new/24_tamagawa_station.jpg',
        'img/stations_photo_new/24_tamagawa_cream.jpg',
        'img/stations_photo_new/24_tamagawa_menu.jpg',
      ],
      mapX: '50.6',
      mapY: '8.9',
      facilities : "park,shop,restaurant,toiletf",
      official: 'https://www.yutoripark-tamagawa.com/',
    },
  ];